name: Java Build and Docker Push

on:
  push:
    branches: 
      - master
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for Grandle wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Show contents of build/libs
      run: ls -lh build/libs

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: zh0nggg/demo-app:${{ env.IMAGE_TAG }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
